In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Regressore lineare per il riconoscimento del prezzo su fiat 500 usate
### Variabile target: `price`
si vuole stimare il prezzo di fiat 500 usate tramite un regressore lineate addestrate sul seguente dataset: `Used_fiat_500_in_Italy_dataset.csv`

In [2]:
data = pd.read_csv("./Used_fiat_500_in_Italy_dataset.csv")
data

model  engine_power transmission  age_in_days      km  previous_owners  \
0       pop            69       manual         4474   56779                2   
1    lounge            69       manual         2708  160000                1   
2    lounge            69    automatic         3470  170000                2   
3     sport            69       manual         3288  132000                2   
4     sport            69       manual         3712  124490                2   
..      ...           ...          ...          ...     ...              ...   
375  lounge            69       manual         4474   55976                2   
376  lounge            69       manual         4200  134717                1   
377  lounge            69       manual         3470  113344                1   
378     pop            69    automatic         3712  130000                1   
379  lounge            99       manual         4566   96000                1   

           lat       lon  price  
0    45.071079   7.46403   4490  
1    45.069679   7.70492   4500  
2    45.514599   9.28434   4500  
3    41.903221  12.49565   4700  
4    45.532661   9.03892   4790  
..         ...       ...    ...  
375  45.610050   9.24234   5500  
376  44.102020   9.82024   5500  
377  41.003799  16.87294   5500  
378  45.810501   8.96474   5500  
379  44.325890  10.83756   5500  

[380 rows x 9 columns]

In [3]:
np.unique(data["transmission"])

array(['automatic', 'manual'], dtype=object)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   model            380 non-null    object 
 1   engine_power     380 non-null    int64  
 2   transmission     380 non-null    object 
 3   age_in_days      380 non-null    int64  
 4   km               380 non-null    int64  
 5   previous_owners  380 non-null    int64  
 6   lat              380 non-null    float64
 7   lon              380 non-null    float64
 8   price            380 non-null    int64  
dtypes: float64(2), int64(5), object(2)
memory usage: 26.8+ KB


In [5]:
target = data["price"]
feature = ["model","engine_power","transmission","age_in_days","km","previous_owners"]

In [6]:
X = data[feature]
X

model  engine_power transmission  age_in_days      km  previous_owners
0       pop            69       manual         4474   56779                2
1    lounge            69       manual         2708  160000                1
2    lounge            69    automatic         3470  170000                2
3     sport            69       manual         3288  132000                2
4     sport            69       manual         3712  124490                2
..      ...           ...          ...          ...     ...              ...
375  lounge            69       manual         4474   55976                2
376  lounge            69       manual         4200  134717                1
377  lounge            69       manual         3470  113344                1
378     pop            69    automatic         3712  130000                1
379  lounge            99       manual         4566   96000                1

[380 rows x 6 columns]

In [7]:
LabelEncoder_model = LabelEncoder()
X_model = LabelEncoder_model.fit_transform(X["model"].to_numpy().reshape(-1))
X_model

array([1, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 3, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 2, 2, 0, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0, 2, 2, 1, 2,
       0, 1, 1, 0, 2, 1, 0, 1, 1, 2, 1, 0, 0, 1, 2, 0, 2, 1, 1, 1, 1, 0,
       2, 0, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 0, 2, 2, 0, 2, 0, 1, 1, 1, 1,
       2, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 0, 1, 2, 1, 0,
       1, 2, 0, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 2, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 2, 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       2, 0, 2, 1, 0, 0, 2, 0, 0, 2, 1, 0, 1, 1, 0, 2, 2, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 1, 0, 1, 2, 0, 2, 2, 1, 2, 0, 2,

In [8]:
LabelEncoder_transmission = LabelEncoder()
X_transmission = LabelEncoder_transmission.fit_transform(X["transmission"].to_numpy().reshape(-1))
X_transmission

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,

In [11]:
StandardScaler_X = StandardScaler()
X_numeric_norm = StandardScaler_X.fit_transform(X[["engine_power","age_in_days","km","previous_owners"]])
X_numeric_norm

array([[-0.40272567,  0.81059049, -0.96522944,  0.8748317 ],
       [-0.40272567, -0.4195038 ,  1.22847334, -0.91245887],
       [-0.40272567,  0.11126169,  1.4409982 ,  0.8748317 ],
       ...,
       [-0.40272567,  0.11126169,  0.23691739, -0.91245887],
       [-0.40272567,  0.27982501,  0.59089879, -0.91245887],
       [ 2.60584094,  0.87467242, -0.13168571, -0.91245887]])

In [12]:
X_norm = np.column_stack((X_transmission,X_model, X_numeric_norm))
X_norm

array([[ 1.        ,  1.        , -0.40272567,  0.81059049, -0.96522944,
         0.8748317 ],
       [ 1.        ,  0.        , -0.40272567, -0.4195038 ,  1.22847334,
        -0.91245887],
       [ 0.        ,  0.        , -0.40272567,  0.11126169,  1.4409982 ,
         0.8748317 ],
       ...,
       [ 1.        ,  0.        , -0.40272567,  0.11126169,  0.23691739,
        -0.91245887],
       [ 0.        ,  1.        , -0.40272567,  0.27982501,  0.59089879,
        -0.91245887],
       [ 1.        ,  0.        ,  2.60584094,  0.87467242, -0.13168571,
        -0.91245887]])

In [13]:
y = target
y

0      4490
1      4500
2      4500
3      4700
4      4790
       ... 
375    5500
376    5500
377    5500
378    5500
379    5500
Name: price, Length: 380, dtype: int64

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.2, random_state = 42)

In [15]:
model = LinearRegression(fit_intercept=True)

In [16]:
model.fit(X_train, y_train)

LinearRegression()

In [17]:
model.score(X_test, y_test)

0.8836511905604691

In [18]:
model.predict(X_test[:2])

array([4371.16995118, 5367.37190454])

In [101]:
encoder_model = LabelEncoder_model.classes_
encoder_model

array(['lounge', 'pop', 'sport', 'star'], dtype=object)

In [102]:
X_test[:2], y_test[:2]

(array([[ 1.        ,  2.        , -0.40272567,  0.8955687 ,  0.27211151,
         -0.91245887,  0.8644709 , -0.82008644],
        [ 1.        ,  1.        , -0.40272567,  0.40798885, -0.29541486,
         -0.91245887, -0.5240171 ,  0.45114616]]),
 266    4999
 261    4990
 Name: price, dtype: int64)

In [47]:
user_input = np.array(["sport",89, "automatic", 3512, 190000, 2])

In [48]:
user_input[0].reshape(-1)

array(['sport'], dtype='<U5')

In [49]:
user_input_model_encoded = LabelEncoder_model.transform(user_input[0].reshape(-1))
user_input_model_encoded

array([2])

In [50]:
user_input_transmission_encoded = LabelEncoder_transmission.transform(user_input[2].reshape(-1))
user_input_transmission_encoded

array([0])

In [51]:
df = pd.DataFrame([user_input], columns=feature)
df

model engine_power transmission age_in_days      km previous_owners
0  sport           89    automatic        3512  190000               2

In [52]:
user_input_norm = StandardScaler_X.transform(df[["engine_power","age_in_days", "km", "previous_owners"]])
user_input_norm

array([[1.6029854 , 0.14051648, 1.8660479 , 0.8748317 ]])

In [53]:
user_input_to_predict = np.insert(user_input_norm, 0, user_input_model_encoded, axis=1)

user_input_to_predict = np.insert(user_input_to_predict, 2, user_input_transmission_encoded, axis=1)

user_input_to_predict

array([[2.        , 1.6029854 , 0.        , 0.14051648, 1.8660479 ,
        0.8748317 ]])

In [54]:
model.predict(user_input_to_predict)

array([4769.59659949])

In [135]:
%pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [20]:
import joblib

In [21]:

joblib.dump(model, "Linear_regressor_FIAT500.pkl")  # Salva il modello su file


['Linear_regressor_FIAT500.pkl']

In [55]:
encoders = {
    "model": LabelEncoder_model,
    "transmission": LabelEncoder_transmission
}

joblib.dump(encoders, "label_encoders.pkl")

['label_encoders.pkl']

In [56]:
joblib.dump(StandardScaler_X, "standard_scaler.pkl")

['standard_scaler.pkl']